In [ ]:
#Bài 1.2
import math
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print (tich)
np.dot(a,b)
import numpy as np
a = np.array([1,2,-3])
np.linalg.norm(a, 2)
a = np.array([1,2,-3])
np.linalg.norm(a,1)
def chuan(v,k):
  tong = 0
  for i in range(len(v)):
    tong = tong + abs(v[i]**k)
  ketqua = math.pow(tong,1.0/k)
  return ketqua

32


In [ ]:
import math
import numpy as np
from scipy import linalg
a = np.array([1,2,-3])
chuan(a, 1)
np.linalg.norm(a,1)
chuan(a, 2)
np.linalg.norm(a,2)
chuan(a, 3)
np.linalg.norm(a,3)
chuan(a, 1000)
np.linalg.norm(a,1000)
linalg.norm(a)
linalg.norm(a, 100)
linalg.norm(a, 1000)

/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


np.float64(inf)

In [ ]:
#Bài 2
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
MT
v = (1.0/m)*MT.dot(mi)
print (v)

[1.3 0.9 0. ]


In [ ]:
#Bài 3
import numpy as np
A = np.array([[0.998, 0.136],[0.002, 0.864]])
v0 = np.array([[0.95],[0.05]])
vecto =np.linalg.matrix_power(A, 100)
tinh = np.dot(vecto,v0)
print(tinh)

[[0.98550723]
 [0.01449277]]


In [ ]:
import sympy as np
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y])
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [ ]:
#Bài 3.2
import numpy as np
A = np.array([[1, 6],[5, 2]])
u = np.array([[6],[-5]])
Au = np.dot(A,u)
Au =-4 *u
print(Au)

[[-24]
 [ 20]]


In [ ]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])
print (sympy.pretty(nghiem))

[-7.000, 3.000]
[-7, 3]


In [ ]:
#Bài 3.3
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P)
print (P1)
A.dot(P)
P.dot(D)
print (D **2)

[[-0.3  0.9]
 [ 0.3  0.1]]
[[49  0]
 [ 0  9]]


In [ ]:
#Bài tập chương 6
#Câu 1
import numpy as np
a = np.array([1,2,3])
mag = np.linalg.norm(a)
print(mag)

3.7416573867739413


In [ ]:
#Câu 2
import numpy as np
#a)Tính toán khoảng cách giữa 2 vector u và v
u = np.array([1, 2])
v = np.array([3, 4])
khoang_cach = np.linalg.norm(u - v)
print(khoang_cach)
#b)
u = np.linalg.norm(u)
v = np.linalg.norm(v)
np.dot(u, v)
goc = np.dot(u, v) / (u * v)
np.arccos(goc)
print(goc)
#c)Phép chiếu trực giao p với 2 vector u và v cho trước:
S = (np.dot(u, v) / np.dot(v, v)) * v
print(S)

2.8284271247461903
1.0
2.23606797749979
