In [ ]:
# 1.2
#Bài 1
#a)
import numpy as np
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])
x = 2*u-(v+3*w)
print (x)
#b)
x = 0.5*(2*u-v-3*w)
print (x)

[ 18 -11   9  -8]
[ 9.  -5.5  4.5 -4. ]


In [ ]:
#Bài 2
from numpy import linalg
A = np.matrix([[0, -1, 3],[1, 1, 1],[4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print (X)

[ 1. -2. -1.]


In [ ]:
#Bài 3
A = np.matrix([[1,0],[0,0]])
B = np.matrix([[0,0],[0,1]])
from numpy import linalg as LA
LA.inv(A+B)
LA.det(A)
LA.det(B)
LA.det(A+B)

np.float64(1.0)

In [ ]:
#Bài 4
import sympy as sp
x, y = sp.symbols('x y')
A = sp.Matrix([[x, y],[y, x]])
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1],[y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])
A1.T
(A1+A2).T
((A1+A2).T).equals(A1+A2)
c = sp.symbols('c')
print (c*A)
((c*A).T).equals(c*A)

Matrix([[c*x, c*y], [c*y, c*x]])


True

In [ ]:
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([0, 1, 2])
v3 = np.array([-1, 0, 1])
A = np.column_stack((v1, v2, v3))
w = np.array([1, 1, 1])
np.linalg.lstsq(A, w,)

(array([ 5.0000000e-01,  1.2490009e-16, -5.0000000e-01]),
 array([], dtype=float64),
 np.int32(2),
 array([4.37228132e+00, 1.37228132e+00, 1.31914152e-16]))

In [ ]:
#Bài 6
import sympy as sp
v1 = np.array([1, 2, 3])
v2 = np.array([0, 1, 2])
v3 = np.array([-2, 0, 1])
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1-2*c3, 2*c1+c2, 3*c1+2*c2+c3], [c1, c2, c3])

{c1: 0, c2: 0, c3: 0}

In [ ]:
#Bài 7
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
sp.solve([c1+c2-u1,c1-c2-u2])
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: u1/2 + u2/2, c2: u1/2 - u2/2}

In [ ]:
# 2.2
# a
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])
P_caua = (P.T + vecdelta).T
print (P_caua)
# b
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0],[0.0, 2.0]])
P_caub = (P.T @ matran_biendoi + vecdelta).T
print (P_caub)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]
[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [ ]:
# 3.3
import sympy as sp
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
sp.solve([a+3*b-x, 2*a+5*b-y],[a,b])

{a: -5*x + 3*y, b: 2*x - y}

In [ ]:
fu1 = np.array([1,1,2])
fu2 = np.array([4,2,1])
fu = a*fu1 + b*fu2
print (fu)
fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2 # thay giá trị tìm được ở trên vào
print (fu)

[a + 4*b a + 2*b 2*a + b]
[3*x - y -x + y -8*x + 5*y]


In [ ]:
# 3.4
x1, x2, x3 = sp.symbols('x1 x2 x3')
sp.solve([x1+x2-x3, 2*x1+3*x2-x3, 3*x1+5*x2-x3],[x1, x2, x3])

{x1: 2*x3, x2: -x3}

In [ ]:
#3.6
import numpy as np
import math
from scipy import linalg as LA
B = np.matrix([[1.0/math.sqrt(2), 1.0/math.sqrt(2)],[-1.0/math.sqrt(2),1.0/math.sqrt(2)]]) # cos(pi/4)
LA.orth(B)
np.array([[-0.70710678, 0.70710678],[ 0.70710678, 0.70710678]])
1.0/math.sqrt(2)

0.7071067811865475

In [ ]:
#Bài tập chương 4
# Bài 1
import numpy as np
def g(v):
    x, y, z = v
    return np.array([x + y, z + 2, 0])
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
# Kiểm tra tính chất: g(u + v) == g(u) + g(v)
left = g(u + v)
right = g(u) + g(v)
print("g(u + v):", left)
print("g(u) + g(v):", right)
# Kiểm tra thêm: g(c * u) == c * g(u)
c = 2
left2 = g(c * u)
right2 = c * g(u)
print(left2)
print(right2)

g(u + v): [12 11  0]
g(u) + g(v): [12 13  0]
[6 8 0]
[ 6 10  0]


In [ ]:
#Bài 3
from sympy import symbols, Matrix

# Khai báo biến
v1, v2 = symbols('v1 v2')

# Ánh xạ tuyến tính T
T = Matrix([v1 - v2, v1 + 2*v2])

# Viết lại dưới dạng ma trận
B = Matrix([[1, -1], [1, 2]])

# Kiểm tra dạng tuyến tính: T = B * [v1; v2]
x = Matrix([v1, v2])
T == B * x
print("T là ánh xạ tuyến tính vì có thể viết dưới dạng nhân ma trận.")

T là ánh xạ tuyến tính vì có thể viết dưới dạng nhân ma trận.
