In [5]:
#Bài 1.1
import numpy as np
D = np.array([[1,2],[3,4]])
np.copyto(E, D)
E = np.array([[1,2],[3,5]])
np.copyto(E, D)
print(E)

[[1 2]
 [3 4]]


In [8]:
#Bài 1.2
import numpy as np

x = np.array([['a','b'],['c','d']])
y = 'x'
C = np.matrix([[x,y],[1, 2]], dtype=object)
print (C)
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
#Bài 1.3
from numpy import matlib
G = matlib.identity(5)
print (G)
H = matlib.randn(3,2)
print(H)
K = matlib.zeros([4,4]) #  cú pháp: matlib.zeros(shape)
print(K)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[-1.91056253 -0.53263431]
 [-0.58947655  0.76901111]
 [ 0.32329801 -1.23453143]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#Bài 2.2
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
M = np.asmatrix([[1,2],[3,4]])
for i in range(len(c)):
  ci = np.asmatrix([[1,1],[1,0]])
  ci[0, 0] = c[i]
  if (i==0):
    M = ci
  else:
    M = M.dot(ci)
print(M)
print (M[0,0]/M[1,0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [18]:
#3.2
import numpy as np
X = np.array([[1, 1],[1, 2],[1, 3],[1, 4],[1, 5]])
Y = np.array([[2],[3],[4],[4],[6]])
XT = X.transpose()
A1 = XT.dot(X)
A2 = XT.dot(Y)
A = A1.dot(A2)
print(A)

[[1085]
 [3915]]


In [42]:
#Bài tập chương 5
import numpy as np
def bpcuctieu(a):
  b = []
  o1 = []
  for i in range(len(a)):
    o1.append(1.0)
    b.append((i+1)*1.0)
  x = np.array([o1, b])
  u = np.dot(x, x.T)
  y = np.array(a)
  from numpy import linalg
  u_1 =np.linalg.inv(u)
  v = np.dot(u_1, x)
  A = np.dot(v, y)
  return A
dulieu = [10.0, 8,7,5,2]
bpcuctieu(dulieu)

array([12.1, -1.9])