In [9]:
#Bài 1
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b)
C = np.asmatrix(np.random.random( (10,5) ) )
D = np.asmatrix([ [4, 3], [2, 6] ])
F = np.eye(3, k=1)
F = np.eye(3, k=0)
F = np.eye(3, k=-1)
#Các phép xử lý đơn giản
np.linalg.matrix_rank(C)
A.I
linalg.inv(A)
A.T
A.H

matrix([[0.90463681, 0.3167799 ],
        [0.30099969, 0.86066021]])

In [8]:
#Giải các loại phương trình tuyến tính:
linalg.solve(A, b)
E = np.asmatrix(a).T
linalg.lstsq(F, E)

(array([[2.],
        [3.],
        [0.]]),
 array([], dtype=float64),
 2,
 array([1., 1., 0.]))

In [10]:
#Các hàm trên ma trận
np.add(A, D)
np.subtract(A, D)
np.divide(A, D)
A @ D
np.multiply(D, A)
np.dot(A, D)
np.vdot(A, D)
linalg.expm(A)
linalg.logm(A)

array([[-0.16444282,  0.35613416],
       [ 0.37480485, -0.21647467]])

In [12]:
#Bài 2.3
import numpy as np
#Tính ma trận A:
A = np.array([ [0,1], [1,0]])
print(A)
temp = A.dot(A) # tính toan lần thứ 1
print(temp)
k= 6
for i in range(k-1):
  temp = temp.dot(A)
  print (temp)
  print('---')
#Tính ma trận B:
B = np.array([ [0,-1], [-1,0]])
print(B)
temp = B.dot(B) # tính toan lần thứ 1
print(temp)
k= 5
for i in range(k-1):
  temp = temp.dot(B)
  print (temp)
  print('---')
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)
temp = C.dot(C) # tính toan lần thứ 1
print(temp)
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)

[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
#Bài 2.4
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM)
MM = M.dot(M) # tính M3
print (MM)
for i in range(100):
  MM = MM.dot(M)
print (MM)

[[0.7  0.45]
 [0.3  0.55]]
[[0.7  0.45]
 [0.3  0.55]]
[[0.6 0.6]
 [0.4 0.4]]


In [15]:
#Bài3.2:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U
print (P)
print (L)
print (U)
L.dot(U)

[[1. 0.]
 [0. 1.]]
[[1.   0.  ]
 [0.25 1.  ]]
[[0.8   0.3  ]
 [0.    0.625]]


array([[0.8, 0.3],
       [0.2, 0.7]])

In [16]:
#Bài 5:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A) # lúc này temp = õ
print(temp)
temp = temp.dot(A) # lúc này temp = õ
print(temp)
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
  temp = temp.dot(A)
  sumA = sumA + temp
print(temp)
print(sumA)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
