

> Thêm khối trích dẫn



In [ ]:
def scale(a, v):
  return [a*vi for vi in v]
v = [3,5,7]
scale(10, v)

[30, 50, 70]

In [ ]:
#Hàm lấy tổng hai vector:
def sumvector(v, w):
  return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
sumvector(v, w)


[5, 9, 13]

In [ ]:
#Hàm nhân 2 vector:
def dotvector(v, w):
  return sum([vi*wi for (vi, wi) in zip(v, w)])
dotvector(v, w)


68

In [ ]:
#hàm tính chiều dài một vector:
def lenvector(v):
  return dotvector(v,v)
lenvector(w)

56

In [ ]:
# Bài tập 2:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores >= 0
scores < 0
np.select([scores >=0, scores < 0],['so duong', 'so am'], default='unknown')

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [ ]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'],default='unknown')

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

In [ ]:
# Bài tập 3:
import numpy as np
D = np.matrix([[3,4], [5,6]])
print(D)

[[3 4]
 [5 6]]


In [ ]:
import numpy as np
C = np.matrix(np.random.random((5,7)))
print(C)

[[0.7326084  0.04345751 0.83930504 0.99500342 0.00512538 0.26762605
  0.90182084]
 [0.50978329 0.86729371 0.4593415  0.52519936 0.89832173 0.48323964
  0.27823075]
 [0.31433609 0.0384757  0.20047626 0.46846923 0.98831271 0.26270731
  0.49468299]
 [0.96662956 0.04252641 0.90218335 0.93548772 0.74492819 0.66226941
  0.38240266]
 [0.11207477 0.59113132 0.07250262 0.99546224 0.93381498 0.27673764
  0.54779142]]


In [ ]:
import numpy as np
A = np.matrix(np.random.random((2,2)))
print(A)

[[0.99399206 0.15264227]
 [0.74942017 0.45064906]]


In [ ]:
import numpy as np
from scipy import linalg, sparse
b = np.array([(1+5j, 2j, 3j),(4, 5,6)])
B = np.asmatrix(b)
print(B)
print(b)
A = np.matrix(np.random.random((2,2)))
print(A)
print(A.T)
print(A.I)
linalg.inv(A)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[0.86970374 0.90520833]
 [0.31763692 0.28868713]]
[[0.86970374 0.31763692]
 [0.90520833 0.28868713]]
[[ -7.91893271  24.83063187]
 [  8.71304998 -23.85671095]]


array([[ -7.91893271,  24.83063187],
       [  8.71304998, -23.85671095]])

# Mục mới

In [ ]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [ ]:
import numpy as np
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [ ]:
import numpy as np
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M)
print (v_diag)
M_diag = np.diag(v_diag)
print (M_diag)

[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [ ]:
#Bài toán xác định hai ma trận bằng nhau:
#Ta có: hai vector/ma trận bằng nhau khi các phần tử của chúng bằng nhau. import sympy as sp
x = sp.Symbol('x')
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x * x + 2 - 6 * y - 1 - 6 * x + z - 1, 2 * x * x - 8, z**2 + 4 - 5 * y - z - 8], [x, y, z])
x = [1, 2, 3]
y = [1, 2, 3]
print(all([x[i] == y[i] for i in range(len(x))]))
True
y = [1, 2, 4]
print(all([x[i] == y[i] for i in range(len(x))]))
y= [1,2,4]
False

True
False


False

In [ ]:
#Bài 3.2
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print(A)
I6 = np.identity(6)
print(I6)
A.size
np.matrix.diagonal(A)
A = A + I6
print(A)
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)
E = A.dot(D.T)
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print(F)
print(G)
np.linalg.inv(A)
np.linalg.inv(np.linalg.inv(A))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]
[ 71. 198. 325. 452. 579. 706.]
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  8.,  8.,  9., 10., 11.],
       [12., 13., 15., 15., 16., 17.],
       [18., 19., 20., 22., 22., 23.],
       [24., 25., 26., 27., 29., 29.],
       [30., 31., 32., 33., 34., 36.]])

In [ ]:
#Bài 4
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10
for i in range(n):
  b = A.dot(b)
  print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [ ]:
#Bài 5
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [ ]:
#phương pháp nhân ma trận
import numpy as np
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])
A_nghichdao = np.linalg.inv(A)
print(A_nghichdao)

LinAlgError: Singular matrix