In [10]:
#Bài 1
import numpy as np
from numpy.linalg import norm
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])
#a)
tong = A + B
tich_so = 2*A + 3*B
print(tong)
print(tich_so)
#b)
dot_product = np.dot(A, B)
cos_theta = dot_product / (norm(A) * norm(B))
goc =np.degrees(np.arccos(cos_theta))
print("Tích vô hướng A * B:", cos_theta)
print('Góc giữa hai vector A và B: ', round(goc,3))
#c)
CtC = C.T @ C
print(CtC)

[2 3 1 6]
[ 3 11  2 14]
Tích vô hướng A * B: -0.16666666666666666
Góc giữa hai vector A và B:  99.594
[[ 5  2  4]
 [ 2 21 -1]
 [ 4 -1 38]]


In [5]:
#Bài 2
import numpy as np

# Khai báo ma trận M và N
M = np.array([[2,-1, 3, 0],
              [1, 4, -2, 5],
              [0, 2, 6, -3],
              [-1, 0, 1, 4]])

N = np.array([[ 1,  3,  -2,  0],
              [ 4,  -1,  5,  2],
              [ 0,  2, 3, -1],
              [-3, 1, 0, 4]])

# a) Tính tích M × N
tich = M @ N
print(tich)
#b) Tính định thức của ma trận M
try:
    det_M = np.linalg.det(M)
    print(round(det_M, 3))
except np.linalg.LinAlgError as e:
    print(e)

# c) Tính hạng của ma trận N
rank_N = np.linalg.matrix_rank(N)
print(rank_N)

[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
409.0
4


In [6]:
#Bài 3
import numpy as np

# Khai báo ma trận P và vector hệ số tự do
P = np.array([[3, -1, 0, 2],
              [1, 4, -2, 0],
              [0, 1, 5, -1],
              [2, 0, 1, 3]])

b = np.array([6, 8, 3, 7])

# a) Tìm ma trận nghịch đảo của P
try:
    P_nghichdao = np.linalg.inv(P)
    print(P_nghichdao)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch.")

# b) Giải hệ phương trình P * x = b
if 'P_nghichdao' in locals():
    x = P_nghichdao @ b
    print(x)

# c) Kiểm tra lại nghiệm
if 'x' in locals():
    check = P @ x
    print(check)
    print(b)
    print(np.allclose(check, b))


[[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
[2.         1.71428571 0.42857143 0.85714286]
[6. 8. 3. 7.]
[6 8 3 7]
True


In [11]:
#Bài 4
# Khai báo ma trận Q
Q = np.array([[5, -2, 1],
              [0, 3, -2],
              [2, 0, 4]])

# a) Tìm giá trị riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)
print(eigenvalues)

# b) Vector riêng tương ứng
print(eigenvectors)

# c) Chuẩn hóa vector riêng (độ dài = 1)
normed_vectors = eigenvectors / np.linalg.norm(eigenvectors)
print(normed_vectors)

[6.61288786+0.j         2.69355607+1.45615495j 2.69355607-1.45615495j]
[[ 0.75261685+0.j          0.29792621+0.406802j    0.29792621-0.406802j  ]
 [-0.31890305+0.j          0.69283737+0.j          0.69283737-0.j        ]
 [ 0.57608048+0.j          0.1061579 -0.50443928j  0.1061579 +0.50443928j]]
[[ 0.43452354+0.j          0.17200777+0.23486724j  0.17200777-0.23486724j]
 [-0.18411876+0.j          0.40000984+0.j          0.40000984-0.j        ]
 [ 0.33260022+0.j          0.06129029-0.29123816j  0.06129029+0.29123816j]]


In [15]:
#Bài 5
# Ma trận hệ số R và vector hằng số b
R = np.array([[4, -1,  2],
              [1,  3,  -2],
              [0, 2,  5]])
b = np.array([12, 5, 9])

# a) Giải hệ phương trình Rx = b
x = np.linalg.solve(R,b)
print(x)

# b) Kiểm tra khả nghịch và nhân ngược lại
try:
    R_inv = np.linalg.inv(R)
    print(R_inv)
    # Kiểm tra lại nghiệm
    check = R @ x
    print(check)
    print(b)
except np.linalg.LinAlgError:
    print("b) R không khả nghịch.")

# c) Chuẩn Frobenius của R
fro_norm = np.linalg.norm(R, ord='fro')
print(round(fro_norm, 3))

[2.78823529 1.52941176 1.18823529]
[[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
[12.  5.  9.]
[12  5  9]
8.0
